### ISSUE TITLE

训练速度

### ISSUE THREAD

**Issue by www516717402** [zhangnn520/znn_chatglm#1]
感谢开源。遇到个问题，小数据集训练每个迭代耗时1秒，配置不变，仅变大数据集，每个迭代耗时5秒。请问有遇到这种情况吗？按理说数据库大小不会对训练速度造成影响啊

**Comment by zhangnn520** [comment]
没有遇见过，是不是你的显卡显存太小，我用的是a40

**Comment by www516717402** [comment]
已解决
